### ISSUE TITLE
Trying to use pymzml with pyinstaller

### ISSUE THREAD

**Issue by sorenwacker** [pymzml/pymzML#324]
I am running into this error and would like to have some background info about this missing file `psi-ms-1.1.0.obo`:

```
ERROR:ms_mint_app.app:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "pymzml\spec.py", line 201, in _get_encoding_parameters
  File "pymzml\obo.py", line 116, in __getitem__
  File "pymzml\obo.py", line 190, in parseOBO
  File "pymzml\obo.py", line 152, in download_obo
  File "urllib\request.py", line 251, in urlretrieve
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\asdf\\workspace\\ms-mint-app\\pyinstaller\\dist\\Mint\\obo\\psi-ms-1.1.0.obo'
```

It looks like this file is downloaded during runtime, is that correct? Was that changed recently? I just switched from pyinstaller 4 to 5.8, and I am trying to figure out if this is a pyinstaller or pymzml problem.
Thanks

**Comment by sorenwacker** [comment]
There are many obo files on my system, but compressed versions.

`ls dist/Mint/pymzml/obo/`

```
psi-ms-1.0.0.obo.gz   psi-ms-2.19.0.obo.gz  psi-ms-3.03.4.obo.gz  psi-ms-3.5.1.obo.gz       psi-ms-4.0.16.obo.gz
psi-ms-1.10.0.obo.gz  psi-ms-2.20.0.obo.gz  psi-ms-3.03.5.obo.gz  psi-ms-3.52.0.obo.gz      psi-ms-4.0.17.obo.gz
psi-ms-1.1.0.obo.gz   psi-ms-2.20.1.obo.gz  psi-ms-3.10.0.obo.gz  psi-ms-3.53.0.obo.gz      psi-ms-4.0.19.obo.gz
psi-ms-1.11.0.obo.gz  psi-ms-2.20.2.obo.gz  psi-ms-3.11.0.obo.gz  psi-ms-3.54.0.obo.gz      psi-ms-4.0.1.obo.gz
psi-ms-1.12.0.obo.gz  psi-ms-2.2.0.obo.gz   psi-ms-3.12.0.obo.gz  psi-ms-3.55.0.obo.gz      psi-ms-4.0.2.obo.gz
psi-ms-1.12.1.obo.gz  psi-ms-2.21.0.obo.gz  psi-ms-3.13.0.obo.gz  psi-ms-3.56.0.obo.gz      psi-ms-4.0.3.obo.gz
psi-ms-1.12.2.obo.gz  psi-ms-2.2.1.obo.gz   psi-ms-3.14.0.obo.gz  psi-ms-3.57.0.obo.gz      psi-ms-4.0.4.obo.gz
psi-ms-1.13.0.obo.gz  psi-ms-2.22.0.obo.gz  psi-ms-3.15.0.obo.gz  psi-ms-3.58.0.obo.gz      psi-ms-4.0.5.obo.gz
psi-ms-1.13.1.obo.gz  psi-ms-2.23.0.obo.gz  psi-ms-3.16.0.obo.gz  psi-ms-3.59.0.obo.gz      psi-ms-4.0.6.obo.gz
psi-ms-1.13.2.obo.gz  psi-ms-2.23.1.obo.gz  psi-ms-3.17.0.obo.gz  psi-ms-3.60.0.obo.gz      psi-ms-4.0.7.obo.gz
psi-ms-1.14.0.obo.gz  psi-ms-2.24.0.obo.gz  psi-ms-3.18.0.obo.gz  psi-ms-3.61.0.obo.gz      psi-ms-4.0.8.obo.gz
psi-ms-1.15.0.obo.gz  psi-ms-2.25.0.obo.gz  psi-ms-3.19.0.obo.gz  psi-ms-3.6.1.obo.gz       psi-ms-4.0.9.obo.gz
psi-ms-1.16.0.obo.gz  psi-ms-2.25.1.obo.gz  psi-ms-3.20.0.obo.gz  psi-ms-3.62.0.obo.gz      psi-ms-4.1.0.obo.gz
psi-ms-1.17.0.obo.gz  psi-ms-2.26.0.obo.gz  psi-ms-3.21.0.obo.gz  psi-ms-3.63.0.obo.gz      psi-ms-4.1.10.obo.gz
psi-ms-1.17.1.obo.gz  psi-ms-2.27.0.obo.gz  psi-ms-3.22.0.obo.gz  psi-ms-3.64.0.obo.gz      psi-ms-4.1.11.obo.gz
psi-ms-1.18.0.obo.gz  psi-ms-2.28.0.obo.gz  psi-ms-3.23.0.obo.gz  psi-ms-3.65.0.obo.gz      psi-ms-4.1.12.obo.gz
psi-ms-1.18.1.obo.gz  psi-ms-2.29.0.obo.gz  psi-ms-3.24.0.obo.gz  psi-ms-3.65.1.obo.gz      psi-ms-4.1.13.obo.gz
psi-ms-1.18.2.obo.gz  psi-ms-2.30.0.obo.gz  psi-ms-3.25.0.obo.gz  psi-ms-3.66.0.obo.gz      psi-ms-4.1.14.obo.gz
psi-ms-1.2.0.obo.gz   psi-ms-2.3.0.obo.gz   psi-ms-3.27.0.obo.gz  psi-ms-3.66.1.obo.gz      psi-ms-4.1.15.obo.gz
psi-ms-1.2.1.obo.gz   psi-ms-2.31.0.obo.gz  psi-ms-3.28.0.obo.gz  psi-ms-3.67.0.obo.gz      psi-ms-4.1.16.obo.gz
psi-ms-1.3.0.obo.gz   psi-ms-2.3.1.obo.gz   psi-ms-3.29.0.obo.gz  psi-ms-3.68.0.obo.gz      psi-ms-4.1.17.obo.gz
psi-ms-1.3.1.obo.gz   psi-ms-2.32.0.obo.gz  psi-ms-3.30.0.obo.gz  psi-ms-3.69.0.obo.gz      psi-ms-4.1.18.obo.gz
psi-ms-1.4.0.obo.gz   psi-ms-2.33.0.obo.gz  psi-ms-3.31.0.obo.gz  psi-ms-3.70.0.obo.gz      psi-ms-4.1.19.obo.gz
psi-ms-1.5.0.obo.gz   psi-ms-2.33.1.obo.gz  psi-ms-3.32.0.obo.gz  psi-ms-3.70.1.obo.gz      psi-ms-4.1.1.obo.gz
psi-ms-1.6.0.obo.gz   psi-ms-2.34.0.obo.gz  psi-ms-3.33.0.obo.gz  psi-ms-3.71.0.obo.gz      psi-ms-4.1.20.obo.gz
psi-ms-1.7.0.obo.gz   psi-ms-2.35.0.obo.gz  psi-ms-3.34.0.obo.gz  psi-ms-3.7.1.obo.gz       psi-ms-4.1.21.obo.gz
psi-ms-1.8.0.obo.gz   psi-ms-2.36.0.obo.gz  psi-ms-3.35.0.obo.gz  psi-ms-3.72.0.obo.gz      psi-ms-4.1.22.obo.gz
psi-ms-1.8.1.obo.gz   psi-ms-2.37.0.obo.gz  psi-ms-3.36.0.obo.gz  psi-ms-3.7.2.obo.gz       psi-ms-4.1.24.obo.gz
psi-ms-1.9.0.obo.gz   psi-ms-2.38.0.obo.gz  psi-ms-3.37.0.obo.gz  psi-ms-3.73.0.obo.gz      psi-ms-4.1.26.obo.gz
psi-ms-1.9.1.obo.gz   psi-ms-2.39.0.obo.gz  psi-ms-3.38.0.obo.gz  psi-ms-3.7.3.obo.gz       psi-ms-4.1.27.obo.gz
psi-ms-1.9.2.obo.gz   psi-ms-2.40.0.obo.gz  psi-ms-3.39.0.obo.gz  psi-ms-3.74.0.obo.gz      psi-ms-4.1.28.obo.gz
psi-ms-2.0.0.obo.gz   psi-ms-2.4.0.obo.gz   psi-ms-3.40.0.obo.gz  psi-ms-3.75.0.obo.gz      psi-ms-4.1.29.obo.gz
psi-ms-2.01.0.obo.gz  psi-ms-2.50.0.obo.gz  psi-ms-3.4.0.obo.gz   psi-ms-3.76.0_rc1.obo.gz  psi-ms-4.1.2.obo.gz
psi-ms-2.1.0.obo.gz   psi-ms-2.5.0.obo.gz   psi-ms-3.41.0.obo.gz  psi-ms-3.77.0.obo.gz      psi-ms-4.1.30.obo.gz
psi-ms-2.13.0.obo.gz  psi-ms-2.51.0.obo.gz  psi-ms-3.4.1.obo.gz   psi-ms-3.78.0.obo.gz      psi-ms-4.1.31.obo.gz
psi-ms-2.14.0.obo.gz  psi-ms-2.6.0.obo.gz   psi-ms-3.42.0.obo.gz  psi-ms-3.78.0_rc1.obo.gz  psi-ms-4.1.32.obo.gz
psi-ms-2.14.1.obo.gz  psi-ms-2.6.1.obo.gz   psi-ms-3.43.0.obo.gz  psi-ms-3.79.0.obo.gz      psi-ms-4.1.33.obo.gz
psi-ms-2.14.2.obo.gz  psi-ms-2.7.0.obo.gz   psi-ms-3.44.0.obo.gz  psi-ms-3.8.3.obo.gz       psi-ms-4.1.3.obo.gz
psi-ms-2.14.3.obo.gz  psi-ms-2.9.0.obo.gz   psi-ms-3.45.0.obo.gz  psi-ms-3.9.1.obo.gz       psi-ms-4.1.4.obo.gz
psi-ms-2.14.4.obo.gz  psi-ms-3.01.1.obo.gz  psi-ms-3.46.0.obo.gz  psi-ms-4.0.10.obo.gz      psi-ms-4.1.5.obo.gz
psi-ms-2.15.0.obo.gz  psi-ms-3.01.2.obo.gz  psi-ms-3.47.0.obo.gz  psi-ms-4.0.11.obo.gz      psi-ms-4.1.6.obo.gz
psi-ms-2.16.0.obo.gz  psi-ms-3.02.1.obo.gz  psi-ms-3.48.0.obo.gz  psi-ms-4.0.12.obo.gz      psi-ms-4.1.7.obo.gz
psi-ms-2.17.0.obo.gz  psi-ms-3.03.1.obo.gz  psi-ms-3.49.0.obo.gz  psi-ms-4.0.13.obo.gz      psi-ms-4.1.8.obo.gz
psi-ms-2.17.1.obo.gz  psi-ms-3.03.2.obo.gz  psi-ms-3.50.0.obo.gz  psi-ms-4.0.14.obo.gz      psi-ms-4.1.9.obo.gz
psi-ms-2.18.0.obo.gz  psi-ms-3.03.3.obo.gz  psi-ms-3.51.0.obo.gz  psi-ms-4.0.15.obo.gz
```

**Comment by sorenwacker** [comment]
Here is a bit more traceback info:

```
  File "ms_mint\io.py", line 223, in mzml_to_df
  File "numpy\lib\function_base.py", line 2329, in __call__
  File "numpy\lib\function_base.py", line 2407, in _vectorize_call
  File "numpy\lib\function_base.py", line 2367, in _get_ufunc_and_otypes
  File "numpy\lib\function_base.py", line 2324, in func
  File "ms_mint\io.py", line 246, in _extract_mzml
  File "pymzml\spec.py", line 1050, in peaks
  File "pymzml\spec.py", line 209, in _get_encoding_parameters
TypeError: 'NoneType' object is not subscriptable
ERROR:ms_mint_app.app:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "pymzml\spec.py", line 201, in _get_encoding_parameters
  File "pymzml\obo.py", line 116, in __getitem__
  File "pymzml\obo.py", line 190, in parseOBO
  File "pymzml\obo.py", line 152, in download_obo
  File "urllib\request.py", line 251, in urlretrieve
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\asdf\\workspace\\ms-mint-app\\pyinstaller\\dist\\Mint\\obo\\psi-ms-1.1.0.obo'
```

**Comment by sorenwacker** [comment]
it looks like the path is wrong for some unknown reason:

`FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\soere\\workspace\\ms-mint-app\\pyinstaller\\dist\\Mint\\obo\\psi-ms-1.1.0.obo'`

It should be:

`C:\\Users\\soere\\workspace\\ms-mint-app\\pyinstaller\\dist\\Mint\\pymzml\\obo\\psi-ms-1.1.0.obo`

So, it is probably a pyinstaller problem.

**Comment by sorenwacker** [comment]
There is a suggestion from the pyinstaller team:

https://github.com/orgs/pyinstaller/discussions/7474
