### ISSUE TITLE
pymzml 2.0 does not read chromatogram files with arbitrary identifiers

### ISSUE THREAD

**Issue by hroest** [pymzml/pymzML#87]
I fail to read chromatogram files with arbitrary ids such as this one: https://drive.google.com/open?id=1CPasmk0gpVqd6i4Y72_ocri4aL7CvlE2

I expect this to work
```
python -c 'import pymzml
f = "test.mzML"
run = pymzml.run.Reader(f)
run["DECOY_126104_C[160]NVVISGGTGSGK/2_y10"]
```

However I get the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/media/doc/pyenv/py36_bleeding3/lib/python3.6/site-packages/pymzml-2.0.3-py3.6.egg/pymzml/run.py", line 150, in __getitem__
    spectrum = self.info['file_object'][identifier]
  File "/media/doc/pyenv/py36_bleeding3/lib/python3.6/site-packages/pymzml-2.0.3-py3.6.egg/pymzml/file_interface.py", line 106, in __getitem__
    return self.file_handler[identifier]
  File "/media/doc/pyenv/py36_bleeding3/lib/python3.6/site-packages/pymzml-2.0.3-py3.6.egg/pymzml/file_classes/standardMzml.py", line 97, in __getitem__
    identifier
  File "/media/doc/pyenv/py36_bleeding3/lib/python3.6/site-packages/pymzml-2.0.3-py3.6.egg/pymzml/file_classes/standardMzml.py", line 471, in _search_string_identifier
    raise Exception('cant find specified string')
Exception: cant find specified string
```

I think this is because this code assumes that the chromatogram ids will be integers:

https://github.com/pymzml/pymzML/blob/903c207035dbd5ccf1ed9015fe5a6b0b32b8fd9a/pymzml/file_classes/standardMzml.py#L200-L202

**Comment by MKoesters** [comment]
Should be fixed, I'll leave this one open for a few days and then close it if there are no issues with the fix.
Sry, I'm bit busy at the moment so fixing took me some time.
